org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8 -Duser.language=en -Duser.country=US -Duser.timezone=UTC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.warning.mode=all
org.gradle.java.installations.auto-download=false
android.useAndroidX=false
android.nonTransitiveRClass=true
android.nonFinalResIds=true
