plugins { id 'com.android.application' }

android {
    namespace 'com.warden.controlledsandbox'
    compileSdk rootProject.ext.controlledCompileSdk
    buildToolsVersion rootProject.ext.controlledBuildTools

    defaultConfig {
        applicationId 'com.warden.controlledsandbox'
        minSdk rootProject.ext.controlledMinSdk
        targetSdk rootProject.ext.controlledTargetSdk
        versionCode 2
        versionName '0.2.0-development'
    }

    buildTypes {
        debug { applicationIdSuffix '.debug' versionNameSuffix '-debug' }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation project(':sandbox-domain')
    implementation project(':sandbox-contract')
    implementation project(':sandbox-runtime')
}
